const videoData = [
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 1,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'crazy tricks for valorant',
        channel: 'brown boy',
        views: '1K',
        uploaded: '1 day ago',
        verified: false,
        live: false,
        id: 2,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 3,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: true,
        id: 4,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 5,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 6,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: true,
        id: 7,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 8,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 9,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 10,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 11,
    },
    {
        img: 'https://i.ytimg.com/vi/l7TxwBhtTUY/hq720_live.jpg?sqp=CNjfsYAG-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmVNjMQzuOHHknmocydqjEQyedCg',
        logo: 'https://yt3.ggpht.com/ytc/AAUvwnhbzltKjEkb2tlCdRpx2-wjpvBYy_RRMQzNmpSmLQ=s68-c-k-c0x00ffffff-no-rj',
        time: '12:32',
        title: 'lofi hip hop radio - sad & sleepy beats 😴',
        channel: 'the bootleg boy',
        views: '404K',
        uploaded: '6 months ago',
        verified: true,
        live: false,
        id: 12,
    },
]

export default videoData